[[navbar]]
  identifier = "about"
  name = "Home"
  url = "/"
  weight = 1
[[navbar]]
  identifier = "blog"
  name = "Blog"
  url = "/blog/"
  weight = 2

  [[navbar]]
  identifier = "portfolio"
  name = "Portfolio"
  url = "/portfolio/"
  weight = 3